#!/usr/local/bin/python3

import openai
import os
import sys


PROMPT = """
You are a unix terminal assistant.
The user will prompt you will something they need to do in the terminal on macOS.
You will respond with ONLY a command to accomplish the stated goal.

What I need to do: {command}

Run:
"""

def green(string):
  return f"\033[92m{string}\033[0m"

def main():
  command = " ".join(sys.argv[1:])
  completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
      {"role": "user", "content": PROMPT.format(command=command)}
    ],
  )

  completion_result = completion.choices[0].message.content
  # strip backticks and extra whitespace in case the model adds them
  cmd_to_run = completion_result.strip("`").strip()
  print(green(cmd_to_run))
  if input("run command? (y/N): ") == "y":
    os.system(cmd_to_run)

if __name__ == "__main__":
  main()
